version: '3.8'

services:
  app:
    image: node:20.11.0
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "80:3000"
    command: /bin/sh -c "npm install && npm run start"
